site_name: Gover
site_url: https://help.gvr.cm
nav:
    - Overview: 2020/FPS01/main.md
    - Security checks:
      - Password status: 2020/FPS01/gv0001.md
      - Security parameters: 2020/FPS01/gv0004.md
    - Installation: 2020/FPS01/inst.md
    - FAQ: 2020/faq.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
plugins:
  - macros
  - search
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
google_analytics:
  - UA-189272109-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/apps-usage-for-sap-fiori-launchpad
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/fioritracker
  prod:
    gv:
      name: 'Gover'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
      R2020FPS01:
        compatibleCoreRel: SPS03      
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        
  